//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoRSideTracker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en_us")]
        public string Language {
            get {
                return ((string)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState MainWindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["MainWindowState"]));
            }
            set {
                this["MainWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0, 0, 0")]
        public global::System.Drawing.Rectangle MainWindowBounds {
            get {
                return ((global::System.Drawing.Rectangle)(this["MainWindowBounds"]));
            }
            set {
                this["MainWindowBounds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MainWindowShowDebugLog {
            get {
                return ((bool)(this["MainWindowShowDebugLog"]));
            }
            set {
                this["MainWindowShowDebugLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowPlayerDeck {
            get {
                return ((bool)(this["ShowPlayerDeck"]));
            }
            set {
                this["ShowPlayerDeck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowPlayerPlayedCards {
            get {
                return ((bool)(this["ShowPlayerPlayedCards"]));
            }
            set {
                this["ShowPlayerPlayedCards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowPlayerDrawnCards {
            get {
                return ((bool)(this["ShowPlayerDrawnCards"]));
            }
            set {
                this["ShowPlayerDrawnCards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowOpponentPlayedCards {
            get {
                return ((bool)(this["ShowOpponentPlayedCards"]));
            }
            set {
                this["ShowOpponentPlayedCards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowDeckStats {
            get {
                return ((bool)(this["ShowDeckStats"]));
            }
            set {
                this["ShowDeckStats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20, 20")]
        public global::System.Drawing.Point PlayerDeckLocation {
            get {
                return ((global::System.Drawing.Point)(this["PlayerDeckLocation"]));
            }
            set {
                this["PlayerDeckLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220, 20")]
        public global::System.Drawing.Point PlayerPlayedCardsLocation {
            get {
                return ((global::System.Drawing.Point)(this["PlayerPlayedCardsLocation"]));
            }
            set {
                this["PlayerPlayedCardsLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("420, 20")]
        public global::System.Drawing.Point PlayerDrawnCardsLocation {
            get {
                return ((global::System.Drawing.Point)(this["PlayerDrawnCardsLocation"]));
            }
            set {
                this["PlayerDrawnCardsLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("620, 20")]
        public global::System.Drawing.Point OpponentPlayedCardsLocation {
            get {
                return ((global::System.Drawing.Point)(this["OpponentPlayedCardsLocation"]));
            }
            set {
                this["OpponentPlayedCardsLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int DeckTransparency {
            get {
                return ((int)(this["DeckTransparency"]));
            }
            set {
                this["DeckTransparency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideZeroCountInDeck {
            get {
                return ((bool)(this["HideZeroCountInDeck"]));
            }
            set {
                this["HideZeroCountInDeck"] = value;
            }
        }
    }
}
